### ISSUE TITLE
Los scripts del directorio 'source' no son compatibles con Python3

### ISSUE THREAD

**Issue by jgsogo** [Lingwars/GAPLEN#18]
Python3 es el estándard hoy, los scripts que metamos aquí deben funcionar con él (y opcionalmente mantener compatibilidad con Python2).

_Añadiré algunos comentarios sobre los archivos de código fuente_

**Comment by davidam** [comment]
He hecho un pull request.

**Comment by davidam** [comment]
¿Qué tal va este tema? ¿tuvisteis tiempo de revisar el pull request?
